-- AlterTable
ALTER TABLE "User" ADD COLUMN     "currentMonthCubentUnits" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "cubentUnitsLimit" DOUBLE PRECISION NOT NULL DEFAULT 50,
ADD COLUMN     "lastUsageReset" TIMESTAMP(3);

-- AlterTable
ALTER TABLE "UsageAnalytics" ADD COLUMN     "cubentUnits" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "UsageMetrics" ADD COLUMN     "cubentUnits" DOUBLE PRECISION NOT NULL DEFAULT 0;
